CREATE TABLE LIBRARIAN
(E_ID VARCHAR(9) NOT NULL,
F_NAME VARCHAR(15) NOT NULL,
M_NAME VARCHAR(15),
L_NAME VARCHAR(15) NOT NULL,
USERNAME VARCHAR(20) NOT NULL,
P_WORD VARCHAR(20) NOT NULL,
PRIMARY KEY(E_ID),
UNIQUE(USERNAME)
);

CREATE TABLE STUDENT
(M_ID VARCHAR(9) NOT NULL,
SRN VARCHAR(13) NOT NULL,
F_NAME VARCHAR(15) NOT NULL,
M_NAME VARCHAR(15),
L_NAME VARCHAR(15) NOT NULL,
DEPT VARCHAR(5) NOT NULL,
YEAR INT NOT NULL,
SECTION CHAR(1) NOT NULL,
DOB DATE,
E_ID VARCHAR(9) NOT NULL,
PRIMARY KEY(M_ID),
UNIQUE(SRN),
FOREIGN KEY(E_ID) REFERENCES LIBRARIAN(E_ID)
);

CREATE TABLE PUBLISHER
(
P_ID VARCHAR(10) NOT NULL,
P_NAME VARCHAR(20) NOT NULL,
STREET_NO INT NOT NULL,
AREA VARCHAR(10) NOT NULL,
ZIP INT NOT NULL,
PRIMARY KEY(P_ID)
);

CREATE TABLE TITLE
(ISBN VARCHAR(17) NOT NULL,
T_NAME VARCHAR(30) NOT NULL,
EDITION INT NOT NULL,
PRICE DECIMAL(100,2) NOT NULL,
CATEGORY VARCHAR(20) NOT NULL,
P_ID VARCHAR(10) NOT NULL,
PRIMARY KEY(ISBN),
FOREIGN KEY(P_ID) REFERENCES PUBLISHER(P_ID)
);


CREATE TABLE SECTION
(
S_ID VARCHAR(5) NOT NULL,
S_NAME VARCHAR(20) NOT NULL,
RACK_NO INT NOT NULL,
PRIMARY KEY(S_ID)
);

CREATE TABLE AUTHOR
(NAME VARCHAR(20) NOT NULL,
ISBN VARCHAR(17) NOT NULL,
PRIMARY KEY(NAME,ISBN),
FOREIGN KEY(ISBN) REFERENCES TITLE(ISBN)
);

CREATE TABLE BOOK
(ID VARCHAR(20) NOT NULL,
M_ID VARCHAR(9) NOT NULL,
RESERVE_DATE DATE NOT NULL,
S_ID VARCHAR(5) NOT NULL,
BORROW_DATE DATE NOT NULL,
RETURN_DATE DATE NOT NULL,
FINE INT,
ISBN VARCHAR(17) NOT NULL,
E_ID VARCHAR(9) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(M_ID) REFERENCES STUDENT(M_ID),
FOREIGN KEY(S_ID) REFERENCES SECTION(S_ID),
FOREIGN KEY(ISBN) REFERENCES TITLE(ISBN),
FOREIGN KEY(E_ID) REFERENCES LIBRARIAN(E_ID)
);

CREATE TABLE WRITES
(NAME VARCHAR(20) NOT NULL,
ISBN VARCHAR(17) NOT NULL,
PRIMARY KEY(NAME,ISBN),
FOREIGN KEY(NAME) REFERENCES AUTHOR(NAME),
FOREIGN KEY(ISBN) REFERENCES TITLE(ISBN)
);

CREATE  TABLE PUBLISHER_PHONE
(
P_ID VARCHAR(10) NOT NULL,
P_PHONE VARCHAR(12) NOT NULL,
PRIMARY KEY(P_ID,P_PHONE),
FOREIGN KEY(P_ID) REFERENCES PUBLISHER(P_ID)
);

CREATE  TABLE STUDENT_PHONE
(
M_ID VARCHAR(9) NOT NULL,
S_PHONE VARCHAR(12) NOT NULL,
PRIMARY KEY(M_ID,S_PHONE),
FOREIGN KEY(M_ID) REFERENCES STUDENT(M_ID)
);
